### változók
@protocol = http://
@hostname = localhost
@port = 8000
@host = {{protocol}}{{hostname}}:{{port}}
### @token = 12|ibiwTdr77o8ppToh1tBxIkckBNb8ECjIjLgaweTaa757cdef

### teszt
get {{host}}/api/

### post methods
GET url HTTP/1.1  {{host}}/api/instruments
Accept: application/json
Content-Type: application/json

get {{host}}/api/instruments/1

POST  {{host}}/api/instruments
Accept: application/json
Content-Type: application/json

{
    "name": "f3333",
    "description": "Kézzel termelt egészség",
    "brand": "brandike",
    "price": 8000,
    "quantity": 22
}

delete {{host}}/api/instruments/14
Accept: application/json
Content-Type: application/json

{
    "description": "Te ki vagy bogyó",
    "price": 8001
}